#!/bin/bash

SOURCE_BRANCH="master"
SOURCE_COMMIT=`git ls-remote https://github.com/AlexeyAB/darknet.git HEAD | awk '{ print $1 }'`

if [ "$DOCKER_TAG" = "latest" ]; then
  VAR="gpu"
else
  VAR=$DOCKER_TAG
fi

if [[ "$DOCKER_TAG" == *cv* ]]; then
  if [ "$DOCKER_TAG" = "cpu-cv" ] || [ "$DOCKER_TAG" = "cpu-noopt-cv" ]; then
    docker build --build-arg BASE_IMAGE="ubuntu:18.04" \
      --build-arg CONFIG=$VAR \
      --build-arg ADDITIONAL_PACKAGES="libopencv-dev" \
      --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
      --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
      -t $DOCKER_REPO:$DOCKER_TAG .
  else
    docker build \
      --build-arg CONFIG=$VAR \
      --build-arg ADDITIONAL_PACKAGES="libopencv-dev" \
      --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
      --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
      -t $DOCKER_REPO:$DOCKER_TAG .
  fi
else
  if [ "$DOCKER_TAG" = "cpu" ] || [ "$DOCKER_TAG" = "cpu-noopt" ]; then
    docker build --build-arg BASE_IMAGE="ubuntu:18.04" \
      --build-arg CONFIG=$VAR \
      --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
      --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
      -t $DOCKER_REPO:$DOCKER_TAG .
  else
    docker build \
      --build-arg CONFIG=$VAR \
      --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
      --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
      -t $DOCKER_REPO:$DOCKER_TAG .
  fi
fi


